name: Build And Deploy
on:
    push:
        branches:
            - 'main'
    pull_request:
        branches:
            - 'main'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repository
              uses: actions/checkout@v2
              with:
                submodules: recursive
            - name: Setup .NET SDK
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'
            - name: Restore NPM Packages
              run: npm install
            - name: Build DocFX MetaData
              run: npm run docfx
            - name: Build Site
              run: npm run build
            - name: Upload To Server
              uses: easingthemes/ssh-deploy@main
              with:
                SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                ARGS: "-avh -i"
                SOURCE: "_site/"
                REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                REMOTE_USER: ${{ secrets.REMOTE_USER }}
                TARGET: ${{ secrets.REMOTE_TARGET }}
              
              